export function defaultPlayerStats() {
  return {
    flatDamage: 0,
    block: 0,
    lowHpDamage: 0,
    critChance: 0,
    goldMultiplier: 1,
    healOnWinHand: 0,
    bustGuardPerEncounter: 1,
    luckyStart: 0,
    blackjackBonusDamage: 0,
    dealerBustBonusDamage: 0,
    standWinDamage: 0,
    doubleWinDamage: 0,
    firstHandDamage: 0,
    bustBlock: 0,
    chipsOnWinHand: 0,
    chipsOnPush: 0,
    healOnEncounterStart: 0,
    splitWinDamage: 0,
    doubleLossBlock: 0,
    blackjackHeal: 0,
    eliteDamage: 0,
  };
}

export function createProfile() {
  return {
    version: 1,
    totals: {
      runsStarted: 0,
      runsCompleted: 0,
      runsWon: 0,
      runsLost: 0,
      enemiesDefeated: 0,
      handsPlayed: 0,
      damageDealt: 0,
      damageTaken: 0,
      chipsEarned: 0,
      chipsSpent: 0,
      relicsCollected: 0,
      bestFloor: 1,
      bestRoom: 1,
      longestStreak: 0,
      blackjacks: 0,
      doublesWon: 0,
      splitsUsed: 0,
      pushes: 0,
    },
    relicCollection: {},
    runs: [],
  };
}

export function createRuntimeState({ width, height, audioEnabled }) {
  return {
    mode: "menu",
    run: null,
    profile: null,
    savedRunSnapshot: null,
    autosaveTimer: 0,
    encounter: null,
    rewardOptions: [],
    shopStock: [],
    selectionIndex: 0,
    floatingTexts: [],
    cardBursts: [],
    sparkParticles: [],
    handTackles: [],
    flashOverlays: [],
    screenShakeTime: 0,
    screenShakeDuration: 0,
    screenShakePower: 0,
    announcement: "",
    announcementTimer: 0,
    announcementDuration: 0,
    audio: {
      enabled: Boolean(audioEnabled),
      started: false,
      primed: false,
      context: null,
      masterGain: null,
      musicGain: null,
      sfxGain: null,
      musicSound: null,
      musicDuckTimer: 0,
      lastMusicMode: "menu",
    },
    collectionPage: 0,
    pendingTransition: null,
    menuSparks: [],
    handMessageAnchor: null,
    combatLayout: null,
    passiveTooltipTimer: 0,
    worldTime: 0,
    viewport: {
      width,
      height,
      scale: 1,
      cropWorldX: 0,
      portraitZoomed: false,
    },
    visual: {
      disableFx: false,
    },
    lastIntroDialogue: "",
  };
}
